# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Arsenal < Formula
  desc "Local-first manager for curated technical resources (CLI + TUI + web)"
  homepage "https://github.com/edwinupegui/arsenal"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/edwinupegui/arsenal/releases/download/v0.3.0/arsenal_0.3.0_darwin_x86_64.tar.gz"
      sha256 "92aba74e496dc9eaeeb49d101bb3743231d843b7c3e2b9b00c6569e0c497be33"

      define_method(:install) do
        bin.install "arsenal"
        generate_completions_from_executable(bin/"arsenal", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/edwinupegui/arsenal/releases/download/v0.3.0/arsenal_0.3.0_darwin_arm64.tar.gz"
      sha256 "ca7a6a3566a721ee422c7a0609cef658f9812ea09bffbaeb8cf263e56329279a"

      define_method(:install) do
        bin.install "arsenal"
        generate_completions_from_executable(bin/"arsenal", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/edwinupegui/arsenal/releases/download/v0.3.0/arsenal_0.3.0_linux_x86_64.tar.gz"
      sha256 "12bc2e1e9e85a8d35e5c7269de772cbd0e50dd0e1fe0098fb44adba51abacba5"
      define_method(:install) do
        bin.install "arsenal"
        generate_completions_from_executable(bin/"arsenal", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/edwinupegui/arsenal/releases/download/v0.3.0/arsenal_0.3.0_linux_arm64.tar.gz"
      sha256 "1b35df52b10fb09ad9b790e7a288904821404df3945f2f22686db69ec317fa14"
      define_method(:install) do
        bin.install "arsenal"
        generate_completions_from_executable(bin/"arsenal", "completion")
      end
    end
  end

  test do
    system "#{bin}/arsenal", "version"
  end
end
