# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Arsenal < Formula
  desc "Local-first manager for curated technical resources (CLI + TUI + web)"
  homepage "https://github.com/edwinupegui/arsenal"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/edwinupegui/arsenal/releases/download/v0.2.0/arsenal_0.2.0_darwin_x86_64.tar.gz"
      sha256 "9108e8cab2975597bebbe11b023e6c2b37a4410734502525b30e23c9980ee578"

      define_method(:install) do
        bin.install "arsenal"
        generate_completions_from_executable(bin/"arsenal", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/edwinupegui/arsenal/releases/download/v0.2.0/arsenal_0.2.0_darwin_arm64.tar.gz"
      sha256 "5bcf681204ec8a824efbab7a38aab6b1871f5116c7d68d8f0a39914a9a722a71"

      define_method(:install) do
        bin.install "arsenal"
        generate_completions_from_executable(bin/"arsenal", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/edwinupegui/arsenal/releases/download/v0.2.0/arsenal_0.2.0_linux_x86_64.tar.gz"
      sha256 "e98516b0df06684e526be749b78cef2d8aa40f2da16d3808c7b43d60acbda5f8"
      define_method(:install) do
        bin.install "arsenal"
        generate_completions_from_executable(bin/"arsenal", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/edwinupegui/arsenal/releases/download/v0.2.0/arsenal_0.2.0_linux_arm64.tar.gz"
      sha256 "08071e28bd9dd5e66085734cb2abfdd414cf93d85e213abb9f7c270a4990e228"
      define_method(:install) do
        bin.install "arsenal"
        generate_completions_from_executable(bin/"arsenal", "completion")
      end
    end
  end

  test do
    system "#{bin}/arsenal", "version"
  end
end
