# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Arsenal < Formula
  desc "Local-first manager for curated technical resources (CLI + TUI + web)"
  homepage "https://github.com/edwinupegui/arsenal"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/edwinupegui/arsenal/releases/download/v0.1.0/arsenal_0.1.0_darwin_x86_64.tar.gz"
      sha256 "67ef28a87c54ee839bdd56f49d9c4fac9343fb00a5f46858294fdb9e547c7f67"

      define_method(:install) do
        bin.install "arsenal"
        generate_completions_from_executable(bin/"arsenal", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/edwinupegui/arsenal/releases/download/v0.1.0/arsenal_0.1.0_darwin_arm64.tar.gz"
      sha256 "d8974daf0cd93c8dfbd8ff55683eabea707f89eaffe7cc1fc33f3e39a38fc082"

      define_method(:install) do
        bin.install "arsenal"
        generate_completions_from_executable(bin/"arsenal", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/edwinupegui/arsenal/releases/download/v0.1.0/arsenal_0.1.0_linux_x86_64.tar.gz"
      sha256 "ea01021e343edbd561a3f2ed41957ecdf944f04dc500e82c0ad0f4aeea4bffd4"
      define_method(:install) do
        bin.install "arsenal"
        generate_completions_from_executable(bin/"arsenal", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/edwinupegui/arsenal/releases/download/v0.1.0/arsenal_0.1.0_linux_arm64.tar.gz"
      sha256 "065a987b79a68eae127ef82550edcf6078596ad40f62aa3a84d7dc70c5e2a2f9"
      define_method(:install) do
        bin.install "arsenal"
        generate_completions_from_executable(bin/"arsenal", "completion")
      end
    end
  end

  test do
    system "#{bin}/arsenal", "version"
  end
end
